### ISSUE TITLE
Better padding strategy for binary mode

### ISSUE THREAD

**Issue by dloscutoff** [RedwolfPrograms/risky#1]
Idea: instead of padding odd-length programs with a trailing `_` in binary mode, what about padding with a *leading* `_`? Then the `_` wouldn't even need to be trimmed off: it would simply apply the identity function to the program's return value.

I can submit a pull request if you like.

**Comment by Radvylf** [comment]
The problem is, this will break programs that use the original padding method. I guess that's fine though, there aren't that many Risky answers yet.

You can submit the pull request if you want, although it'd require you trying to figure out my awful front end JS :p

**Comment by Radvylf** [comment]
Never mind, I forgot this won't affect string mode (what all existing programs I'm aware of use), so it shouldn't break anything. Went ahead and made the change.

Thanks for the suggestion!
