### ISSUE TITLE
Is Sort supposed to modify the list?

### ISSUE THREAD

**Issue by dloscutoff** [RedwolfPrograms/risky#2]
Consider the program `__+1_` (concatenate the list of inputs and the list of inputs sorted). With an input of `[3,2,1]`, I expected the result to be `[3,2,1,1,2,3]`; however, instead, I got `[1,2,3,1,2,3]`. [Try it online!](https://redwolfprograms.github.io/risky?p=WyJfXysxXyIsIlszLDIsMV0iLDBd)

I'm guessing the `1` monad sorts the input list in place, meaning that every other reference to `_` becomes the sorted version. Under some circumstances, the modification of `_` can also affect `?`: [Try it online!](https://redwolfprograms.github.io/risky?p=WyIxXzJfPyIsIlszLDIsMV0iLDBd)

I suspect this behavior is not intentional, but I'm not 100% sure, so I'm phrasing this issue as a question.

**Comment by Radvylf** [comment]
If anything's modifying in place, that's not intentional. I'll fix that in a minute.

**Comment by Radvylf** [comment]
It's been slightly more than a minute, but I fixed it.
